const pool = require('../config/db');

// Sample cars across every category so the frontend has data to display.
// New cars added here are inserted on the next `npm run db:seed`; cars that
// already exist (matched by name) are left untouched.
// Cars with no images show the category's stock photo on the site.
// No admin account is created anywhere in this app.
const sampleCars = [
  {
    name: 'Toyota Corolla',
    brand: 'Toyota',
    type: 'sedan',
    seats: 5,
    transmission: 'automatic',
    fuel: 'petrol',
    price_per_day: 6500,
    currency: 'INR',
    images: ['https://placehold.co/800x500?text=Toyota+Corolla'],
    description: 'Comfortable, fuel-efficient sedan - a favourite for city and highway trips.',
    is_featured: true,
    featured_order: 1,
  },
  {
    name: 'Honda City',
    brand: 'Honda',
    type: 'sedan',
    seats: 5,
    transmission: 'automatic',
    fuel: 'petrol',
    price_per_day: 7000,
    currency: 'INR',
    images: ['https://placehold.co/800x500?text=Honda+City'],
    description: 'Spacious and smooth, ideal for family outings and business travel.',
    is_featured: false,
    featured_order: null,
  },
  {
    name: 'Suzuki Swift',
    brand: 'Suzuki',
    type: 'hatchback',
    seats: 5,
    transmission: 'automatic',
    fuel: 'petrol',
    price_per_day: 5500,
    currency: 'INR',
    images: ['https://placehold.co/800x500?text=Suzuki+Swift'],
    description: 'Small, agile and cheap to run - perfect for exploring the city.',
    is_featured: false,
    featured_order: null,
  },
  {
    name: 'Toyota Fortuner',
    brand: 'Toyota',
    type: 'suv',
    seats: 7,
    transmission: 'automatic',
    fuel: 'diesel',
    price_per_day: 18000,
    currency: 'INR',
    images: ['https://placehold.co/800x500?text=Toyota+Fortuner'],
    description: 'Rugged 7-seater SUV for long journeys and rough roads.',
    is_featured: true,
    featured_order: 2,
  },
  {
    name: 'Hyundai Verna',
    brand: 'Hyundai',
    type: 'sedan',
    seats: 5,
    transmission: 'automatic',
    fuel: 'petrol',
    price_per_day: 6800,
    currency: 'INR',
    images: [],
    description: 'Stylish sedan with a roomy cabin and a smooth ride on long drives.',
    is_featured: false,
    featured_order: null,
  },
  {
    name: 'Maruti Suzuki Ciaz',
    brand: 'Maruti Suzuki',
    type: 'sedan',
    seats: 5,
    transmission: 'manual',
    fuel: 'petrol',
    price_per_day: 5800,
    currency: 'INR',
    images: [],
    description: 'Generous legroom and boot space at an easy price.',
    is_featured: false,
    featured_order: null,
  },
  {
    name: 'Skoda Slavia',
    brand: 'Skoda',
    type: 'sedan',
    seats: 5,
    transmission: 'automatic',
    fuel: 'petrol',
    price_per_day: 7500,
    currency: 'INR',
    images: [],
    description: 'Solid, quiet and quick - great for business trips.',
    is_featured: false,
    featured_order: null,
  },
  {
    name: 'Mahindra Scorpio-N',
    brand: 'Mahindra',
    type: 'suv',
    seats: 7,
    transmission: 'manual',
    fuel: 'diesel',
    price_per_day: 12000,
    currency: 'INR',
    images: [],
    description: 'Tough 7-seater that handles highways and hill roads with ease.',
    is_featured: false,
    featured_order: null,
  },
  {
    name: 'Hyundai Creta',
    brand: 'Hyundai',
    type: 'suv',
    seats: 5,
    transmission: 'automatic',
    fuel: 'petrol',
    price_per_day: 9000,
    currency: 'INR',
    images: [],
    description: 'Comfortable compact SUV packed with features for city and highway.',
    is_featured: false,
    featured_order: null,
  },
  {
    name: 'Kia Seltos',
    brand: 'Kia',
    type: 'suv',
    seats: 5,
    transmission: 'automatic',
    fuel: 'diesel',
    price_per_day: 9500,
    currency: 'INR',
    images: [],
    description: 'Premium compact SUV with a high driving position and big boot.',
    is_featured: false,
    featured_order: null,
  },
  {
    name: 'Tata Nexon EV',
    brand: 'Tata',
    type: 'suv',
    seats: 5,
    transmission: 'automatic',
    fuel: 'electric',
    price_per_day: 8500,
    currency: 'INR',
    images: [],
    description: 'Quiet, zero-emission compact SUV - charge included for city use.',
    is_featured: false,
    featured_order: null,
  },
  {
    name: 'Maruti Suzuki Baleno',
    brand: 'Maruti Suzuki',
    type: 'hatchback',
    seats: 5,
    transmission: 'manual',
    fuel: 'petrol',
    price_per_day: 4500,
    currency: 'INR',
    images: [],
    description: 'Roomy premium hatchback that is light on fuel.',
    is_featured: false,
    featured_order: null,
  },
  {
    name: 'Hyundai i20',
    brand: 'Hyundai',
    type: 'hatchback',
    seats: 5,
    transmission: 'automatic',
    fuel: 'petrol',
    price_per_day: 5000,
    currency: 'INR',
    images: [],
    description: 'Comfortable, well-equipped hatchback for city errands.',
    is_featured: false,
    featured_order: null,
  },
  {
    name: 'Tata Tiago',
    brand: 'Tata',
    type: 'hatchback',
    seats: 5,
    transmission: 'manual',
    fuel: 'cng',
    price_per_day: 3500,
    currency: 'INR',
    images: [],
    description: 'Our most affordable car - easy to park and very cheap to run.',
    is_featured: false,
    featured_order: null,
  },
  {
    name: 'Toyota Innova Crysta',
    brand: 'Toyota',
    type: 'van',
    seats: 7,
    transmission: 'manual',
    fuel: 'diesel',
    price_per_day: 14000,
    currency: 'INR',
    images: [],
    description: 'The go-to people carrier for family trips and airport runs.',
    is_featured: false,
    featured_order: null,
  },
  {
    name: 'Maruti Suzuki Ertiga',
    brand: 'Maruti Suzuki',
    type: 'van',
    seats: 7,
    transmission: 'manual',
    fuel: 'cng',
    price_per_day: 8000,
    currency: 'INR',
    images: [],
    description: 'Budget-friendly 7-seater for groups on a budget.',
    is_featured: false,
    featured_order: null,
  },
  {
    name: 'Force Urbania',
    brand: 'Force',
    type: 'van',
    seats: 13,
    transmission: 'manual',
    fuel: 'diesel',
    price_per_day: 22000,
    currency: 'INR',
    images: [],
    description: 'Spacious 13-seater for group tours, weddings and pilgrimages.',
    is_featured: false,
    featured_order: null,
  },
  {
    name: 'Mercedes-Benz E-Class',
    brand: 'Mercedes-Benz',
    type: 'luxury',
    seats: 5,
    transmission: 'automatic',
    fuel: 'diesel',
    price_per_day: 35000,
    currency: 'INR',
    images: [],
    description: 'Executive luxury sedan for weddings, VIP pickups and special days.',
    is_featured: false,
    featured_order: null,
  },
  {
    name: 'BMW 5 Series',
    brand: 'BMW',
    type: 'luxury',
    seats: 5,
    transmission: 'automatic',
    fuel: 'petrol',
    price_per_day: 38000,
    currency: 'INR',
    images: [],
    description: 'Sporty, refined luxury sedan that makes an entrance.',
    is_featured: false,
    featured_order: null,
  },
  {
    name: 'Toyota Camry Hybrid',
    brand: 'Toyota',
    type: 'luxury',
    seats: 5,
    transmission: 'automatic',
    fuel: 'hybrid',
    price_per_day: 20000,
    currency: 'INR',
    images: [],
    description: 'Whisper-quiet hybrid luxury with a plush rear seat.',
    is_featured: false,
    featured_order: null,
  },
  {
    name: 'Toyota Hilux',
    brand: 'Toyota',
    type: 'pickup',
    seats: 5,
    transmission: 'automatic',
    fuel: 'diesel',
    price_per_day: 16000,
    currency: 'INR',
    images: [],
    description: 'Go-anywhere 4x4 pickup for rough terrain and cargo.',
    is_featured: false,
    featured_order: null,
  },
  {
    name: 'Isuzu D-Max V-Cross',
    brand: 'Isuzu',
    type: 'pickup',
    seats: 5,
    transmission: 'manual',
    fuel: 'diesel',
    price_per_day: 12500,
    currency: 'INR',
    images: [],
    description: 'Rugged double-cab pickup for adventure trips and heavy loads.',
    is_featured: false,
    featured_order: null,
  },
  {
    name: 'Mahindra Bolero Pik-Up',
    brand: 'Mahindra',
    type: 'pickup',
    seats: 2,
    transmission: 'manual',
    fuel: 'diesel',
    price_per_day: 6000,
    currency: 'INR',
    images: [],
    description: 'Workhorse pickup for moving goods and furniture.',
    is_featured: false,
    featured_order: null,
  },
];

async function main() {
  if (!pool) {
    console.error('ERROR: DATABASE_URL is not set.');
    console.error('Copy .env.example to .env and put your database URL in it, then run this again.');
    process.exitCode = 1;
    return;
  }

  try {
    const { rows } = await pool.query('SELECT name FROM cars');
    const existing = new Set(rows.map((r) => r.name.toLowerCase()));
    const toInsert = sampleCars.filter((car) => !existing.has(car.name.toLowerCase()));

    const insert = `
      INSERT INTO cars
        (name, brand, type, seats, transmission, fuel, price_per_day, currency, images, description, is_featured, featured_order)
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
    `;
    for (const car of toInsert) {
      await pool.query(insert, [
        car.name,
        car.brand,
        car.type,
        car.seats,
        car.transmission,
        car.fuel,
        car.price_per_day,
        car.currency,
        car.images,
        car.description,
        car.is_featured,
        car.featured_order,
      ]);
    }
    const skipped = sampleCars.length - toInsert.length;
    console.log(`SUCCESS: added ${toInsert.length} sample cars (${skipped} already existed and were skipped).`);
  } catch (err) {
    console.error('ERROR: seed failed.');
    console.error('Details: ' + err.message);
    process.exitCode = 1;
  } finally {
    await pool.end();
    console.log('Database connection closed.');
  }
}

main();
